-- Postgres schema for InFeed.
-- Replaces the prior Airtable backing store. Auto-applied on server startup via
-- src/db/index.js → initSchema(). CREATE IF NOT EXISTS makes this idempotent —
-- safe to re-run on every boot.
--
-- Design notes:
--   - Primary keys are TEXT (uuid v4) generated by the app, not Postgres-managed.
--     Some synthetic IDs (e.g. `import-${leadId}`) aren't valid uuids, so the
--     TEXT type keeps them portable.
--   - JSONB is used for any nested data (messages, drafts, notes, scenario) so
--     we don't need separate join tables — readable rows + queryable via ->>.
--   - Foreign keys cascade on DELETE so removing a lead also removes its
--     conversations + actions automatically; no manual cleanup needed.
--   - `updated_at` is maintained by a trigger on each table that has it, so
--     callers don't have to remember to set it.

CREATE TABLE IF NOT EXISTS leads (
  id                     TEXT PRIMARY KEY,
  linkedin_url           TEXT,
  name                   TEXT,
  role                   TEXT,
  company                TEXT,
  sender_id              TEXT,
  tags                   JSONB DEFAULT '[]'::jsonb,
  stage                  TEXT  DEFAULT 'cold',
  funnel_stage           TEXT  DEFAULT 'cold_opener',
  sentiment              TEXT  DEFAULT 'neutral',
  last_routing_decision  JSONB,
  last_asset_sent        TEXT,
  credits_used           INT     DEFAULT 0,
  credits_total          INT     DEFAULT 20,
  trial_started          BOOLEAN DEFAULT false,
  trial_expired          BOOLEAN DEFAULT false,
  call_booked            BOOLEAN DEFAULT false,
  converted              BOOLEAN DEFAULT false,
  campaign_id            TEXT,
  current_step_index     INT     DEFAULT 0,
  last_step_at           TIMESTAMPTZ,
  notes                  JSONB DEFAULT '{}'::jsonb,
  notes_updated_at       TIMESTAMPTZ,
  workspace_id           TEXT  DEFAULT 'infeed',
  created_at             TIMESTAMPTZ DEFAULT NOW(),
  updated_at             TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS conversations (
  id           TEXT PRIMARY KEY,
  -- Lead may be deleted out-of-band; conversations follow the lead.
  lead_id      TEXT REFERENCES leads(id) ON DELETE CASCADE,
  sender_id    TEXT,
  messages     JSONB DEFAULT '[]'::jsonb,
  drafts       JSONB DEFAULT '[]'::jsonb,
  status       TEXT  DEFAULT 'active',
  workspace_id TEXT  DEFAULT 'infeed',
  created_at   TIMESTAMPTZ DEFAULT NOW(),
  updated_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS actions (
  id              TEXT PRIMARY KEY,
  type            TEXT,
  -- ON DELETE SET NULL because we want the action history to survive a lead/
  -- conversation deletion (for analytics) — just orphaned.
  lead_id         TEXT REFERENCES leads(id)         ON DELETE SET NULL,
  conversation_id TEXT REFERENCES conversations(id) ON DELETE SET NULL,
  data            JSONB DEFAULT '{}'::jsonb,
  result          TEXT,
  workspace_id    TEXT  DEFAULT 'infeed',
  timestamp       TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS training (
  id            TEXT PRIMARY KEY,
  type          TEXT  DEFAULT 'draft',
  scenario      JSONB DEFAULT '{}'::jsonb,
  chosen        TEXT,
  original      TEXT,
  selected_text TEXT,
  feedback      TEXT,
  rating        TEXT,
  thread        JSONB DEFAULT '[]'::jsonb,
  question      TEXT,
  option_index  INT     DEFAULT -1,
  is_custom     BOOLEAN DEFAULT false,
  avatar        TEXT,
  is_canonical  BOOLEAN DEFAULT false,
  source        TEXT  DEFAULT 'training',
  workspace_id  TEXT  DEFAULT 'infeed',
  timestamp     TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ratings (
  id              TEXT PRIMARY KEY,
  conversation_id TEXT REFERENCES conversations(id) ON DELETE SET NULL,
  lead_name       TEXT,
  message_text    TEXT,
  rating          TEXT,
  category        TEXT,
  feedback        TEXT,
  was_auto_sent   BOOLEAN DEFAULT false,
  workspace_id    TEXT    DEFAULT 'infeed',
  timestamp       TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS voice_dna (
  id             TEXT PRIMARY KEY,
  workspace_id   TEXT NOT NULL,
  dna            JSONB DEFAULT '{}'::jsonb,
  based_on_count INT   DEFAULT 0,
  model          TEXT,
  source_counts  JSONB DEFAULT '{}'::jsonb,
  generated_at   TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for the hot paths (lookup by lead, by workspace, by conversation).
CREATE INDEX IF NOT EXISTS idx_leads_workspace      ON leads(workspace_id);
CREATE INDEX IF NOT EXISTS idx_leads_linkedin       ON leads(linkedin_url);
CREATE INDEX IF NOT EXISTS idx_leads_campaign       ON leads(campaign_id);
CREATE INDEX IF NOT EXISTS idx_conv_lead            ON conversations(lead_id);
CREATE INDEX IF NOT EXISTS idx_conv_workspace       ON conversations(workspace_id);
CREATE INDEX IF NOT EXISTS idx_actions_lead         ON actions(lead_id);
CREATE INDEX IF NOT EXISTS idx_actions_conv         ON actions(conversation_id);
CREATE INDEX IF NOT EXISTS idx_actions_workspace    ON actions(workspace_id);
CREATE INDEX IF NOT EXISTS idx_actions_type         ON actions(type);
CREATE INDEX IF NOT EXISTS idx_training_workspace   ON training(workspace_id);
CREATE INDEX IF NOT EXISTS idx_training_avatar      ON training(avatar);
CREATE INDEX IF NOT EXISTS idx_ratings_workspace    ON ratings(workspace_id);
CREATE INDEX IF NOT EXISTS idx_voice_dna_workspace  ON voice_dna(workspace_id, generated_at DESC);

-- Auto-maintain updated_at on rows that have it. Avoids forgetting to set it
-- in app code on every update.
CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS leads_touch         ON leads;
DROP TRIGGER IF EXISTS conversations_touch ON conversations;
CREATE TRIGGER leads_touch         BEFORE UPDATE ON leads
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER conversations_touch BEFORE UPDATE ON conversations
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
